/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import attributes.Doctor;
import attributes.DoctorDirectory;
import attributes.Hospital;
import attributes.HospitalDirectory;
import attributes.SystemAdmin;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dheer
 */
public class SuggestedHospitalPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuggestedHospitalPanel
     */
     JPanel rightLayout;
    SystemAdmin systemAdmin;
    String community;
    HospitalDirectory hospitalDirectory;
    DoctorDirectory doctorDirectory;
    public SuggestedHospitalPanel(JPanel rightLayout,SystemAdmin systemAdmin, String community) {
         this.rightLayout=rightLayout;
        this.systemAdmin=systemAdmin;
        this.community=community;
        
        initComponents();
        this.doctorDirectory= systemAdmin.getDoctorDirectory();
         this.hospitalDirectory= systemAdmin.getDoctorDirectory().getDoctor().getHospitalDirectory();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Id", "Doctor Id", "Community", "City"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void jButton9jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton1ActionPerformed
      rightLayout.remove(this);
        CardLayout layout = (CardLayout) rightLayout.getLayout();
        layout.previous(rightLayout);
    }//GEN-LAST:event_jButton9jButton1ActionPerformed

    public void table() {
           DefaultTableModel tbl = (DefaultTableModel)table.getModel();
        tbl.setRowCount(0);
        
        for(Hospital doc: hospitalDirectory.getHospitalDirectory()){
          Object[] r =new Object[7];
          if(community.equalsIgnoreCase(doc.getCommunity()) || community.equalsIgnoreCase(doc.getCity())){
          r[0]= doc.getHospitalName();
          r[1]=doc;
          for(Doctor d: doctorDirectory.getDoctorDirectory()){
              if(doc.getHospitalId().equalsIgnoreCase(d.getHosiptalId())){
                   r[2]="D00"+d.getDoctorId();
              }
          }
         
          r[3]= doc.getCommunity();
          r[4]=doc.getCity();
          tbl.addRow(r);}
    }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
